volumes:
  prometheus-data:

services:
  app-sd:
    build: .
    ports:
      - "8080:8080"

  app-java:
    build: example
    volumes:
      - "./application.properties:/app/application.properties"
    ports:
      - "8081:8080"

  app-java2:
    build: example
    volumes:
      - "./application-2.properties:/app/application.properties"
    ports:
      - "8083:8080"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./alert-rules.yml:/etc/prometheus/alert-rules.yml"
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
      - "prometheus-data:/prometheus"

  alertmanager:
    image: quay.io/prometheus/alertmanager
    command: --config.file=/alertmanager.yml
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager.yml:/alertmanager.yml